=== jovancevic123/XWT_2022/KT1/A-1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

    <xs:element name="zahtev">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="prijava" type="TPrijava"/>
                <xs:element name="podnosilac" type="TPodnosilac"/>
                <xs:element minOccurs="0" name="punomocnik" type="TLice"/>
                <xs:element name="autorsko_delo" type="TAutorskoDelo"/>
                <xs:element name="prilozi">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element maxOccurs="unbounded" name="prilog" type="TPrilog"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType abstract="true" name="TLice">
        <xs:sequence>
            <xs:element name="kontakt" type="TKontakt"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TPrijava">
        <xs:sequence>
            <xs:element name="broj_prijave" type="xs:positiveInteger"/>
            <xs:element name="datum_podnosenja" type="xs:date"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TFizickoLice">
        <xs:complexContent>
            <xs:extension base="TLice">
                <xs:sequence>
                    <xs:element name="ime" type="xs:string"/>
                    <xs:element name="prezime" type="xs:string"/>
                    <xs:element name="drzavljanstvo" type="xs:string"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="TPravnoLice">
        <xs:complexContent>
            <xs:extension base="TLice">
                <xs:sequence>
                    <xs:element name="poslovno_ime" type="xs:string"/>
                    <xs:element name="sediste" type="xs:string"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="TAutorskoDelo">
        <xs:sequence>
            <xs:element name="naslov" type="xs:string"/>
            <xs:element name="delo_prerade" type="TDeloPrerade"/>
            <xs:element name="vrsta_dela" type="xs:string"/>
            <xs:element name="forma_zapisa_dela" type="xs:string"/>
            <xs:element name="stvoreno_u_radnom_odnosu">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="da"/>
                        <xs:enumeration value="ne"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="nacin_koriscenja" type="xs:string"/>
            <xs:element minOccurs="0" name="autori">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element form="qualified" maxOccurs="unbounded" name="autor"
                            type="TAutor"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="anoniman_autor">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="da"/>
                        <xs:enumeration value="ne"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TDeloPrerade">
        <xs:sequence>
            <xs:element name="naslov_dela_prerade" type="xs:string"/>
            <xs:element name="autori">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element maxOccurs="unbounded" name="autor" type="TAutor"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TAutor">
        <xs:complexContent>
            <xs:extension base="TFizickoLice">
                <xs:sequence>
                    <xs:element name="adresa" type="TAdresa"/>
                    <xs:element name="pseudonim" type="xs:string"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="TAdresa">
        <xs:all>
            <xs:element name="ulica" type="xs:string"/>
            <xs:element name="broj" type="xs:positiveInteger"/>
            <xs:element name="postanski_broj">
                <xs:simpleType>
                    <xs:restriction base="xs:int">
                        <xs:minInclusive value="11000"/>
                        <xs:maxInclusive value="40000"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="mesto" type="xs:string"/>
            <xs:element name="drzava" type="xs:string"/>
        </xs:all>
    </xs:complexType>
    <xs:complexType name="TPodnosilac">
        <xs:complexContent>
            <xs:extension base="TLice">
                <xs:attribute name="podnosilac_je_autor">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="da"/>
                            <xs:enumeration value="ne"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:attribute>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="TPrilog">
        <xs:attribute name="vrsta_priloga"/>
        <xs:attribute name="src"/>
    </xs:complexType>
    <xs:complexType name="TKontakt">
        <xs:all>
            <xs:element name="telefon" type="xs:string"/>
            <xs:element name="email" type="xs:string"/>
            <xs:element minOccurs="0" name="fax" type="xs:string"/>
        </xs:all>
    </xs:complexType>
</xs:schema>

=== jovancevic123/XWT_2022/KT1/A-1-generated.xml
<?xml version="1.0" encoding="UTF-8"?>
<zahtev xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="A-1.xsd">
    <prijava>
        <broj_prijave></broj_prijave>
        <datum_podnosenja></datum_podnosenja>
    </prijava>
    <podnosilac>
        <kontakt>
            <telefon></telefon>
            <email></email>
        </kontakt>
    </podnosilac>
    <autorsko_delo>
        <naslov></naslov>
        <delo_prerade>
            <naslov_dela_prerade></naslov_dela_prerade>
            <autori>
                <autor>
                    <kontakt>
                        <telefon></telefon>
                        <email></email>
                    </kontakt>
                    <ime></ime>
                    <prezime></prezime>
                    <drzavljanstvo></drzavljanstvo>
                    <adresa>
                        <ulica></ulica>
                        <broj></broj>
                        <postanski_broj></postanski_broj>
                        <mesto></mesto>
                        <drzava></drzava>
                    </adresa>
                    <pseudonim></pseudonim>
                </autor>
            </autori>
        </delo_prerade>
        <vrsta_dela></vrsta_dela>
        <forma_zapisa_dela></forma_zapisa_dela>
        <stvoreno_u_radnom_odnosu></stvoreno_u_radnom_odnosu>
        <nacin_koriscenja></nacin_koriscenja>
        <anoniman_autor></anoniman_autor>
    </autorsko_delo>
    <prilozi>
        <prilog/>
    </prilozi>
</zahtev>
