=== jovancevic123/XWT_2022/KT1/P-1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

    <xs:element name="zahtev">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="prijava" type="TPrijava"/>
                <xs:element name="zavod" type="TZavod"/>
                <xs:element name="patent" type="TPatent"/>
                <xs:element name="podnosioci">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="podnosioc"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="pronalazaci">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="pronalazac"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="polje6" type="TPolje6"/>
                <xs:element name="ranije_prijave">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element maxOccurs="unbounded" minOccurs="0" name="ranija_prijava"
                                type="TRanija_Prijava"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="nacin_dostavljanja">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="elektronska_forma"/>
                            <xs:enumeration value="papirna_forma"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element minOccurs="0" name="adresa_dostave" type="TAdresa"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="adresa" type="TAdresa"/>
    <xs:complexType name="TPrijava">
        <xs:sequence>
            <xs:element name="broj_prijave" type="xs:positiveInteger"/>
            <xs:element name="datum_prijema" type="xs:date"/>
            <xs:element name="datum_podnosenja" type="xs:date"/>
            <xs:element name="priznati_datum_podnosenja" type="xs:date"/>
            <xs:element name="vrsta_prijave">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="dopunska"/>
                        <xs:enumeration value="izdvojena"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TZavod">
        <xs:sequence>
            <xs:element name="naziv" type="xs:string"/>
            <xs:element ref="adresa"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TPatent">
        <xs:sequence>
            <xs:element name="naziv_pronalaska_srb" type="xs:string"/>
            <xs:element name="naziv_pronalaska_eng" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:element name="kontakt">
        <xs:complexType>
            <xs:all>
                <xs:element name="telefon" type="xs:string"/>
                <xs:element name="email" type="xs:string"/>
                <xs:element minOccurs="0" name="fax" type="xs:string"/>
            </xs:all>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="TPolje6">
        <xs:sequence>
            <xs:element name="uloga">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="punomocnik_za_zastupanje"/>
                        <xs:enumeration value="punomocnik_za_prijem_pismena"/>
                        <xs:enumeration value="zajednicki_predstavnik"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element ref="adresa"/>
            <xs:element ref="kontakt"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TAdresa">
        <xs:all>
            <xs:element name="ulica" type="xs:string"/>
            <xs:element name="broj" type="xs:positiveInteger"/>
            <xs:element name="postanski_broj">
                <xs:simpleType>
                    <xs:restriction base="xs:int">
                        <xs:minInclusive value="11000"/>
                        <xs:maxInclusive value="40000"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="mesto" type="xs:string"/>
            <xs:element name="drzava" type="xs:string"/>
        </xs:all>
    </xs:complexType>
    <xs:complexType name="TRanija_Prijava">
        <xs:sequence>
            <xs:element name="broj_prijave" type="xs:positiveInteger"/>
            <xs:element name="datum_podnosenja" type="xs:date"/>
            <xs:element name="dvoslovna_oznaka" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== jovancevic123/XWT_2022/P1 aplikacija/xml-backend-p1/src/main/resources/xml/P-1-generated.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<?xml-stylesheet type="text/xsl" href="bookstore.xsl"?>
<zahtev xmlns="http://www.ftn.uns.ac.rs/xwt"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.ftn.uns.ac.rs/xwt file:/C:/Users/Joco/Desktop/IV/XML/Projekat/XWT_2022/xml-backend-p1/data/P-1.xsd">
    <prijava>
        <broj_prijave>1</broj_prijave>
        <datum_prijema>2022-11-25</datum_prijema>
        <priznati_datum_podnosenja>2022-11-26</priznati_datum_podnosenja>
        <vrsta_prijave>dopunska</vrsta_prijave>
    </prijava>
    <zavod>
        <naziv>Zavod za intelektualnu svojinu</naziv>
        <adresa>
            <ulica>Kneginje Ljubice</ulica>
            <broj>5</broj>
            <postanski_broj>11000</postanski_broj>
            <mesto>Beograd</mesto>
            <drzava>Srbija</drzava>
        </adresa>
    </zavod>
    <pronalazak>
        <naziv_pronalaska_srb>Naziv na srpskom je srb</naziv_pronalaska_srb>
        <naziv_pronalaska_eng>Naziv na engleskom</naziv_pronalaska_eng>
    </pronalazak>

    <podnosilac pronalazac="false">
        <drzavljanstvo>srpsko</drzavljanstvo>
        <lice xsi:type="TPravnoLice">
            <adresa>
                <ulica>Vojvode Stepe</ulica>
                <broj>1</broj>
                <postanski_broj>21000</postanski_broj>
                <mesto>Novi Sad</mesto>
                <drzava>Srbija</drzava>
            </adresa>
            <kontakt>
                <telefon>021 824854</telefon>
                <email>aktiva@gmail.com</email>
            </kontakt>
            <poslovno_ime>Aktiva DOO</poslovno_ime>
        </lice>
    </podnosilac>
    <pronalazac naveden_u_prijavi="true">
        <lice xsi:type="TFizickoLice">
            <adresa>
                <ulica>Kralja Petra I</ulica>
                <broj>17</broj>
                <postanski_broj>21203</postanski_broj>
                <mesto>Veternik</mesto>
                <drzava>Srbija</drzava>
            </adresa>
            <kontakt>
                <telefon>0631899381</telefon>
                <email>jovancevicjovan5@gmail.com</email>
            </kontakt>
            <ime>Jovan</ime>
            <prezime>Jovancevic</prezime>
        </lice>
    </pronalazac>
    <punomoc>
        <tip>punomocnik_za_zastupanje</tip>
        <lice xsi:type="TFizickoLice">
            <adresa>
                <ulica>Omladinska</ulica>
                <broj>15</broj>
                <postanski_broj>21203</postanski_broj>
                <mesto>Veternik</mesto>
                <drzava>Srbija</drzava>
            </adresa>
            <kontakt>
                <telefon>062123789</telefon>
                <email>milanpanic@gmail.com</email>
            </kontakt>
            <ime>Milan</ime>
            <prezime>Panic</prezime>
        </lice>
    </punomoc>
    <ranije_prijave>
        <ranija_prijava>
            <broj_prijave>123</broj_prijave>
            <datum_podnosenja>2022-07-07</datum_podnosenja>
            <dvoslovna_oznaka>hl</dvoslovna_oznaka>
        </ranija_prijava>
        <ranija_prijava>
            <broj_prijave>123</broj_prijave>
            <datum_podnosenja>2022-07-07</datum_podnosenja>
            <dvoslovna_oznaka>hl</dvoslovna_oznaka>
        </ranija_prijava>
    </ranije_prijave>
    <nacin_dostavljanja>elektronska_forma</nacin_dostavljanja>
</zahtev>

=== jovancevic123/XWT_2022/KT1/P-1-generated.xml
<?xml version="1.0" encoding="UTF-8"?>
<zahtev xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="file:/C:/Users/Joco/Desktop/IV/XML/Projekat/XWT_2022/KT1/P-1.xsd">
    <prijava>
        <broj_prijave></broj_prijave>
        <datum_prijema></datum_prijema>
        <priznati_datum_podnosenja></priznati_datum_podnosenja>
        <vrsta_prijave></vrsta_prijave>
    </prijava>
    <zavod>
        <naziv></naziv>
        <adresa>
            <ulica></ulica>
            <broj></broj>
            <postanski_broj></postanski_broj>
            <mesto></mesto>
            <drzava></drzava>
        </adresa>
    </zavod>
    <pronalazak>
        <naziv_pronalaska_srb></naziv_pronalaska_srb>
        <naziv_pronalaska_eng></naziv_pronalaska_eng>
    </pronalazak>
    <podnosilac>
        <adresa>
            <ulica></ulica>
            <broj></broj>
            <postanski_broj></postanski_broj>
            <mesto></mesto>
            <drzava></drzava>
        </adresa>
        <kontakt>
            <telefon></telefon>
            <email></email>
        </kontakt>
        <drzavljanstvo></drzavljanstvo>
    </podnosilac>
    <pronalazac>
        <adresa>
            <ulica></ulica>
            <broj></broj>
            <postanski_broj></postanski_broj>
            <mesto></mesto>
            <drzava></drzava>
        </adresa>
        <kontakt>
            <telefon></telefon>
            <email></email>
        </kontakt>
    </pronalazac>
    <punomoc>
        <tip></tip>
        <adresa>
            <ulica></ulica>
            <broj></broj>
            <postanski_broj></postanski_broj>
            <mesto></mesto>
            <drzava></drzava>
        </adresa>
        <kontakt>
            <telefon></telefon>
            <email></email>
        </kontakt>
    </punomoc>
    <ranije_prijave></ranije_prijave>
    <nacin_dostavljanja></nacin_dostavljanja>
</zahtev>
