=== jovancevic123/XWT_2022/KT1/ZH-1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    targetNamespace="http://www.ftn.uns.ac.rs/xwt" xmlns="http://www.ftn.uns.ac.rs/xwt">

    <xs:element name="zahtev">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="naziv" type="xs:string"/>
                <xs:element name="zavod" type="TZavod"/>
                <xs:element name="podnosilac" type="TLice"/>
                <xs:element name="punomocnik" type="TLice"/>
                <xs:element name="zig" type="TZig"/>
                <xs:element name="placene_takse">
                    <xs:complexType>
                        <xs:sequence maxOccurs="unbounded" minOccurs="0">
                            <xs:element name="taksa" type="TTaksa"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="prilozi" type="TPrilozi"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="TAdresa">
        <xs:all>
            <xs:element name="ulica" type="xs:string"/>
            <xs:element name="broj" type="xs:positiveInteger"/>
            <xs:element name="postanski_broj">
                <xs:simpleType>
                    <xs:restriction base="xs:int">
                        <xs:minInclusive value="11000"/>
                        <xs:maxInclusive value="40000"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="mesto" type="xs:string"/>
            <xs:element name="drzava" type="xs:string"/>
        </xs:all>
    </xs:complexType>
    <xs:complexType name="TZavod">
        <xs:sequence>
            <xs:element name="naziv" type="xs:string"/>
            <xs:element name="adresa" type="TAdresa"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TKontakt">
        <xs:all>
            <xs:element name="telefon" type="xs:string"/>
            <xs:element name="email" type="xs:string"/>
            <xs:element minOccurs="0" name="fax" type="xs:string"/>
        </xs:all>
    </xs:complexType>
    <xs:complexType abstract="true" name="TLice">
        <xs:sequence>
            <xs:element name="adresa" type="TAdresa"/>
            <xs:element name="kontakt" type="TKontakt"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TZnak">
        <xs:sequence>
            <xs:element name="tip_znaka">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="verbalni_znak"/>
                        <xs:enumeration value="graficki_znak"/>
                        <xs:enumeration value="kombinovani_znak"/>
                        <xs:enumeration value="trodimenzionalni_znak"/>
                        <xs:enumeration value="drugi_znak"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="izgled_znaka">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:string">
                            <xs:attribute name="src"/>
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
            <xs:element name="boje">
                <xs:complexType>
                    <xs:sequence maxOccurs="unbounded" minOccurs="0">
                        <xs:element name="boja" type="xs:string"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="opis_znaka" type="xs:string"> </xs:element>
            <xs:element name="transliteracija_znaka" type="xs:string" minOccurs="0"/>
            <xs:element name="prevod_znaka" type="xs:string" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TZig">
        <xs:sequence>
            <xs:element name="tip_ziga">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="individualni_zig"/>
                        <xs:pattern value=""/>
                        <xs:enumeration value="kolektivni_zig"/>
                        <xs:enumeration value="zig_garancije"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="newElement" type="TZnak"/>
            <xs:element name="brojevi_klasa_robe">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="broj" type="xs:positiveInteger"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="zatrazeno_pravo" type="xs:string"/>
            <xs:element name="broj_prijave_ziga" type="xs:positiveInteger"/>
            <xs:element name="datum_podnosenja" type="xs:date"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TTaksa">
        <xs:sequence>
            <xs:element name="tip_takse">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="osnovna_taksa"/>
                        <xs:enumeration value="za____klasa"/>
                        <xs:enumeration value="za_graficko_resenje"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="iznos">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:double">
                            <xs:attribute name="valuta"/>
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TPrilozi">
        <xs:sequence>
            <xs:element name="primerak_znaka">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:string">
                            <xs:attribute name="src"/>
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
            <xs:element name="spisak_robe_i_usluga">
                <xs:complexType>
                    <xs:sequence maxOccurs="unbounded" minOccurs="0">
                        <xs:element name="roba">
                            <xs:complexType>
                                <xs:simpleContent>
                                    <xs:extension base="xs:string">
                                        <xs:attribute name="src"/>
                                    </xs:extension>
                                </xs:simpleContent>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="punomocje">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:string">
                            <xs:attribute name="src"/>
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
            <xs:element name="generalno_punomocje">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:string">
                            <xs:attribute name="src"/>
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
            <xs:element name="punomocje_naknadno_dostavljeno">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:string">
                            <xs:attribute name="src"/>
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
            <xs:element name="opsti_akt">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:string">
                            <xs:attribute name="src"/>
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
            <xs:element name="dokaz_o_pravu_prvenstva">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:string">
                            <xs:attribute name="src"/>
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
            <xs:element name="dokaz_o_uplati_takse">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:string">
                            <xs:attribute name="src"/>
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TFizickoLice">
        <xs:complexContent>
            <xs:extension base="TLice">
                <xs:sequence>
                    <xs:element name="ime" type="xs:string"/>
                    <xs:element name="prezime" type="xs:string"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="TPravnoLice">
        <xs:complexContent>
            <xs:extension base="TLice">
                <xs:sequence>
                    <xs:element name="poslovno_ime" type="xs:string"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
</xs:schema>

=== jovancevic123/XWT_2022/xml-backend-zh-1/src/main/resources/xml/ZH-1-generated.xml
<zahtev xmlns="http://www.ftn.uns.ac.rs/xwt" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.ftn.uns.ac.rs/xwt ZH-1.xsd">
    <naziv/>
    <zavod>
        <naziv/>
        <adresa>
            <ulica>Rumenacki put</ulica>
            <broj>125</broj>
            <postanski_broj>21000</postanski_broj>
            <mesto>Novi Sad</mesto>
            <drzava>Srbija</drzava>
        </adresa>
    </zavod>
    <podnosilac xsi:type="TFizickoLice">
        <adresa>
            <ulica>Pancevacka</ulica>
            <broj>1</broj>
            <postanski_broj>21000</postanski_broj>
            <mesto>Novi Sad</mesto>
            <drzava>Srbija</drzava>
        </adresa>
        <kontakt>
            <telefon>061444999</telefon>
            <email>darkomitrovic@gmail.com</email>
            <fax>324</fax>
        </kontakt>
        <ime>Darko</ime>
        <prezime>Mitrovic</prezime>
    </podnosilac>
    <punomocnik xsi:type="TFizickoLice">
        <adresa>
            <ulica>Brace Ribnikar</ulica>
            <broj>21</broj>
            <postanski_broj>21000</postanski_broj>
            <mesto>Novi Sad</mesto>
            <drzava>Srbija</drzava>
        </adresa>
        <kontakt>
            <telefon>065222333</telefon>
            <email>predragantonic@gmail.com</email>
            <fax>3412</fax>
        </kontakt>
        <ime>Predrag</ime>
        <prezime>Antonic</prezime>
    </punomocnik>
    <zig>
        <tip_ziga>individualni_zig</tip_ziga>
        <znak>
            <tip_znaka>graficki_znak</tip_znaka>
            <izgled_znaka/>
            <boje>
                <boja>crna</boja>
                <boja>zelena</boja>
            </boje>
            <opis_znaka>lep</opis_znaka>
        </znak>
        <brojevi_klasa_robe>
            <broj>1</broj>
            <broj>25</broj>
        </brojevi_klasa_robe>
        <zatrazeno_pravo>gdsa</zatrazeno_pravo>
        <broj_prijave_ziga>1</broj_prijave_ziga>
        <datum_podnosenja>2020-10-10</datum_podnosenja>
    </zig>
    <placene_takse>
        <taksa>
            <tip_takse>osnovna_taksa</tip_takse>
            <iznos>4000</iznos>
        </taksa>
        <taksa>
            <tip_takse>za_graficko_resenje</tip_takse>
            <iznos>2000</iznos>
        </taksa>
    </placene_takse>
    <prilozi>
        <primerak_znaka/>
        <spisak_robe_i_usluga/>
        <punomocje/>
        <generalno_punomocje/>
        <punomocje_naknadno_dostavljeno/>
        <opsti_akt/>
        <dokaz_o_pravu_prvenstva/>
        <dokaz_o_uplati_takse/>
    </prilozi>
</zahtev>

=== jovancevic123/XWT_2022/KT1/ZH-1-generated.xml
<?xml version="1.0" encoding="UTF-8"?>
<zahtev xmlns="http://www.ftn.uns.ac.rs/xwt"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.ftn.uns.ac.rs/xwt ZH-1.xsd">
    <naziv></naziv>
    <zavod>
        <naziv></naziv>
        <adresa>
            <ulica></ulica>
            <broj></broj>
            <postanski_broj></postanski_broj>
            <mesto></mesto>
            <drzava></drzava>
        </adresa>
    </zavod>
    <podnosilac>
        <adresa>
            <ulica></ulica>
            <broj></broj>
            <postanski_broj></postanski_broj>
            <mesto></mesto>
            <drzava></drzava>
        </adresa>
        <kontakt>
            <telefon></telefon>
            <email></email>
        </kontakt>
    </podnosilac>
    <punomocnik>
        <adresa>
            <ulica></ulica>
            <broj></broj>
            <postanski_broj></postanski_broj>
            <mesto></mesto>
            <drzava></drzava>
        </adresa>
        <kontakt>
            <telefon></telefon>
            <email></email>
        </kontakt>
    </punomocnik>
    <zig>
        <tip_ziga></tip_ziga>
        <newElement>
            <tip_znaka></tip_znaka>
            <izgled_znaka></izgled_znaka>
            <boje></boje>
            <opis_znaka></opis_znaka>
        </newElement>
        <brojevi_klasa_robe>
            <broj></broj>
        </brojevi_klasa_robe>
        <zatrazeno_pravo></zatrazeno_pravo>
        <broj_prijave_ziga></broj_prijave_ziga>
        <datum_podnosenja></datum_podnosenja>
    </zig>
    <placene_takse></placene_takse>
    <prilozi>
        <primerak_znaka></primerak_znaka>
        <spisak_robe_i_usluga></spisak_robe_i_usluga>
        <punomocje></punomocje>
        <generalno_punomocje></generalno_punomocje>
        <punomocje_naknadno_dostavljeno></punomocje_naknadno_dostavljeno>
        <opsti_akt></opsti_akt>
        <dokaz_o_pravu_prvenstva></dokaz_o_pravu_prvenstva>
        <dokaz_o_uplati_takse></dokaz_o_uplati_takse>
    </prilozi>
</zahtev>
