=== jovancevic123/XWT_2022/xml-backend/src/main/resources/xml/A-1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    targetNamespace="http://www.ftn.uns.ac.rs/xwt" xmlns:zah="http://www.ftn.uns.ac.rs/xwt">

    <xs:element name="zahtev">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="prijava" type="zah:TPrijava"/>
                <xs:element name="podnosilac" type="zah:TPodnosilac"/>
                <xs:element minOccurs="0" name="punomocnik" type="zah:TLice"/>
                <xs:element name="autorsko_delo" type="zah:TAutorskoDelo"/>
                <xs:element name="prilozi">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element maxOccurs="unbounded" name="prilog" type="zah:TPrilog"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="zavod" type="zah:TZavod"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType abstract="true" name="TLice">
        <xs:sequence>
            <xs:element name="kontakt" type="zah:TKontakt"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TPrijava">
        <xs:sequence>
            <xs:element name="broj_prijave" type="xs:positiveInteger"/>
            <xs:element name="datum_podnosenja" type="xs:date"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TFizickoLice">
        <xs:complexContent>
            <xs:extension base="zah:TLice">
                <xs:sequence>
                    <xs:element name="ime" type="xs:string"/>
                    <xs:element name="prezime" type="xs:string"/>
                    <xs:element name="adresa" type="zah:TAdresa"/>
                    <xs:element name="drzavljanstvo" type="xs:string"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="TPravnoLice">
        <xs:complexContent>
            <xs:extension base="zah:TLice">
                <xs:sequence>
                    <xs:element name="poslovno_ime" type="xs:string"/>
                    <xs:element name="sediste" type="xs:string"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="TAutorskoDelo">
        <xs:sequence>
            <xs:element name="naslov" type="xs:string"/>
            <xs:element name="delo_prerade" type="zah:TDeloPrerade"/>
            <xs:element name="vrsta_dela" type="xs:string"/>
            <xs:element name="forma_zapisa_dela" type="xs:string"/>
            <xs:element name="stvoreno_u_radnom_odnosu">
                <xs:simpleType>
                    <xs:restriction base="xs:boolean"> </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="nacin_koriscenja" type="xs:string"/>
            <xs:element minOccurs="0" name="autori">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element form="qualified" maxOccurs="unbounded" name="autor"
                            type="zah:TAutor"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="anoniman_autor">
                <xs:simpleType>
                    <xs:restriction base="xs:boolean"> </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TDeloPrerade">
        <xs:sequence>
            <xs:element name="naslov_dela_prerade" type="xs:string"/>
            <xs:element name="autori" minOccurs="0">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element maxOccurs="unbounded" name="autor" type="zah:TAutor"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TAutor">
        <xs:complexContent>
            <xs:extension base="zah:TFizickoLice">
                <xs:sequence>
                    <xs:element name="pseudonim" type="xs:string" minOccurs="0"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="TAdresa">
        <xs:all>
            <xs:element name="ulica" type="xs:string"/>
            <xs:element name="broj" type="xs:positiveInteger"/>
            <xs:element name="postanski_broj">
                <xs:simpleType>
                    <xs:restriction base="xs:int">
                        <xs:minInclusive value="11000"/>
                        <xs:maxInclusive value="40000"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="mesto" type="xs:string"/>
            <xs:element name="drzava" type="xs:string"/>
        </xs:all>
    </xs:complexType>
    <xs:complexType name="TPrilog">
        <xs:attribute name="vrsta_priloga"/>
        <xs:attribute name="src"/>
    </xs:complexType>
    <xs:complexType name="TKontakt">
        <xs:all>
            <xs:element name="telefon" type="xs:string"/>
            <xs:element name="email" type="xs:string"/>
            <xs:element minOccurs="0" name="fax" type="xs:string"/>
        </xs:all>
    </xs:complexType>
    <xs:complexType name="TZavod">
        <xs:sequence>
            <xs:element name="naziv" type="xs:string"/>
            <xs:element name="adresa" type="zah:TAdresa"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TPodnosilac">
        <xs:sequence>
            <xs:element name="lice" type="zah:TLice"/>
        </xs:sequence>
        <xs:attribute name="podnosilac_je_autor" type="xs:boolean"> </xs:attribute>
    </xs:complexType>
</xs:schema>

=== jovancevic123/XWT_2022/xml-backend/src/main/resources/xml/A-1-generated.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<?xml-stylesheet type="text/xsl" href="xslt.xsl"?>
<zahtev xmlns="http://www.ftn.uns.ac.rs/xwt"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.ftn.uns.ac.rs/xwt A-1.xsd">
    <prijava>
        <broj_prijave>12</broj_prijave>
        <datum_podnosenja>2022-12-15</datum_podnosenja>
    </prijava>
    <podnosilac podnosilac_je_autor="true">
        <lice xsi:type="TFizickoLice">
            <kontakt>
                <telefon>0628977742</telefon>
                <email>dd@gmail.com</email>
            </kontakt>
            <ime>Dragan</ime>
            <prezime>Dragic</prezime>
            <adresa>
                <ulica>Bul. oslobođenja</ulica>
                <broj>25</broj>
                <postanski_broj>21211</postanski_broj>
                <mesto>Novi Sad</mesto>
                <drzava>Srbija</drzava>
            </adresa>
            <drzavljanstvo>Srpsko</drzavljanstvo>
        </lice>
    </podnosilac>
    <autorsko_delo>
        <naslov>Nova knjiga</naslov>
        <delo_prerade>
            <naslov_dela_prerade>Stara knjiga</naslov_dela_prerade>
            <autori>
                <autor>
                    <kontakt>
                        <telefon>0632153945</telefon>
                        <email>pera@gmail.com</email>
                    </kontakt>
                    <ime>Pera</ime>
                    <prezime>Peric</prezime>
                    <adresa>
                        <ulica>Miše Dimitrijevića</ulica>
                        <broj>54</broj>
                        <postanski_broj>21000</postanski_broj>
                        <mesto>Novi Sad</mesto>
                        <drzava>Srbija</drzava>
                    </adresa>
                    <drzavljanstvo>Srpsko</drzavljanstvo>
                </autor>
            </autori>
        </delo_prerade>
        <vrsta_dela>književno delo</vrsta_dela>
        <forma_zapisa_dela>štampani tekst</forma_zapisa_dela>
        <stvoreno_u_radnom_odnosu>true</stvoreno_u_radnom_odnosu>
        <nacin_koriscenja></nacin_koriscenja>
        <autori>
            <autor>
                <kontakt>
                    <telefon>0628977742</telefon>
                    <email>dd@gmail.com</email>
                </kontakt>
                <ime>Dragan</ime>
                <prezime>Dragic</prezime>
                <adresa>
                    <ulica>Bul. oslobođenja</ulica>
                    <broj>24</broj>
                    <postanski_broj>21211</postanski_broj>
                    <mesto>Novi Sad</mesto>
                    <drzava>Srbija</drzava>
                </adresa>
                <drzavljanstvo>Srpsko</drzavljanstvo>
                <pseudonim>Dragi</pseudonim>
            </autor>
        </autori>
        <anoniman_autor>false</anoniman_autor>
    </autorsko_delo>
    <prilozi>
        <prilog vrsta_priloga="opis autorskog dela" src="Putanja do opisa"/>
    </prilozi>
    <zavod>
        <naziv>Zavod za intelektualnu svojinu</naziv>
        <adresa>
            <ulica>Kneginje Ljubice</ulica>
            <broj>5</broj>
            <postanski_broj>11000</postanski_broj>
            <mesto>Beograd</mesto>
            <drzava>Srbija</drzava>
        </adresa>
    </zavod>
</zahtev>

=== jovancevic123/XWT_2022/xml-backend/src/main/resources/static/rdf.xml
<?xml version="1.0" encoding="UTF-8"?><?xml-stylesheet type="text/xsl" href="xslt.xsl"?><zahtev xmlns:sh="https://schema.org/" xmlns:pred="http://www.ftn.uns.ac.rs/rdf/examples/predicate/" xmlns:xs="http://www.w3.org/2001/XMLSchema#" xmlns:a1="http://www.ftn.uns.ac.rs/xwt" about="http://www.ftn.uns.ac.rs/xwt/zahtev" vocab="http://www.ftn.uns.ac.rs/rdf/examples/predicate/" xsi:schemaLocation="http://www.ftn.uns.ac.rs/xwt A-1.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <prijava xmlns="http://www.ftn.uns.ac.rs/xwt">
        <BrojPrijave xmlns="" datatype="xs:string" property="pred:broj_prijave">12</BrojPrijave>
        <DatumPodnosenja xmlns="" datatype="xs:string" property="pred:datum_podnosenja">2022-12-15</DatumPodnosenja>
    </prijava>
    <podnosilac xmlns="http://www.ftn.uns.ac.rs/xwt" podnosilac_je_autor="true">
        <lice xsi:type="TFizickoLice">
            <kontakt>
                <telefon>0628977742</telefon>
                <PodnosilacEmail xmlns="" datatype="xs:string" property="pred:podnosilac_email">dd@gmail.com</PodnosilacEmail>
            </kontakt>
            <ime>Dragan</ime>
            <prezime>Dragic</prezime>
            <adresa>
                <ulica>Bul. oslobođenja</ulica>
                <broj>25</broj>
                <postanski_broj>21211</postanski_broj>
                <mesto>Novi Sad</mesto>
                <drzava>Srbija</drzava>
            </adresa>
            <drzavljanstvo>Srpsko</drzavljanstvo>
        </lice>
    </podnosilac>
    <autorsko_delo xmlns="http://www.ftn.uns.ac.rs/xwt">
        <NaslovDela xmlns="" datatype="xs:string" property="pred:naslov_dela">Nova knjiga</NaslovDela>
        <delo_prerade>
            <naslov_dela_prerade>Stara knjiga</naslov_dela_prerade>
            <autori>
                <autor>
                    <kontakt>
                        <telefon>0632153945</telefon>
                        <email>pera@gmail.com</email>
                    </kontakt>
                    <ime>Pera</ime>
                    <prezime>Peric</prezime>
                    <adresa>
                        <ulica>Miše Dimitrijevića</ulica>
                        <broj>54</broj>
                        <postanski_broj>21000</postanski_broj>
                        <mesto>Novi Sad</mesto>
                        <drzava>Srbija</drzava>
                    </adresa>
                    <drzavljanstvo>Srpsko</drzavljanstvo>
                </autor>
            </autori>
        </delo_prerade>
        <vrsta_dela>književno delo</vrsta_dela>
        <forma_zapisa_dela>štampani tekst</forma_zapisa_dela>
        <stvoreno_u_radnom_odnosu>true</stvoreno_u_radnom_odnosu>
        <nacin_koriscenja/>
        <autori>
            <autor>
                <kontakt>
                    <telefon>0628977742</telefon>
                    <AutorEmail xmlns="" datatype="xs:string" property="pred:autor_email">dd@gmail.com</AutorEmail>
                </kontakt>
                <ime>Dragan</ime>
                <prezime>Dragic</prezime>
                <adresa>
                    <ulica>Bul. oslobođenja</ulica>
                    <broj>24</broj>
                    <postanski_broj>21211</postanski_broj>
                    <mesto>Novi Sad</mesto>
                    <drzava>Srbija</drzava>
                </adresa>
                <drzavljanstvo>Srpsko</drzavljanstvo>
                <pseudonim>Dragi</pseudonim>
            </autor>
        </autori>
        <anoniman_autor>false</anoniman_autor>
    </autorsko_delo>
    <prilozi xmlns="http://www.ftn.uns.ac.rs/xwt">
        <prilog src="Putanja do opisa" vrsta_priloga="opis autorskog dela"/>
    </prilozi>
    <zavod xmlns="http://www.ftn.uns.ac.rs/xwt">
        <naziv>Zavod za intelektualnu svojinu</naziv>
        <adresa>
            <ulica>Kneginje Ljubice</ulica>
            <broj>5</broj>
            <postanski_broj>11000</postanski_broj>
            <mesto>Beograd</mesto>
            <drzava>Srbija</drzava>
        </adresa>
    </zavod>
</zahtev>

=== jovancevic123/XWT_2022/xml-backend/data/A-1-generated.xml
<?xml version="1.0" encoding="UTF-8"?>
<zahtev xmlns="http://www.ftn.uns.ac.rs/xwt"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.ftn.uns.ac.rs/xwt A-1.xsd">
    <prijava>
        <broj_prijave>12</broj_prijave>
        <datum_podnosenja>2022-12-15</datum_podnosenja>
    </prijava>
    <podnosilac>
        <lice xsi:type="TFizickoLice">
            <kontakt>
                <telefon></telefon>
                <email></email>
            </kontakt>
            <ime>Mihal</ime>
            <prezime></prezime>
            <drzavljanstvo></drzavljanstvo>
        </lice>
    </podnosilac>
    <autorsko_delo>
        <naslov></naslov>
        <delo_prerade>
            <naslov_dela_prerade></naslov_dela_prerade>
        </delo_prerade>
        <vrsta_dela></vrsta_dela>
        <forma_zapisa_dela></forma_zapisa_dela>
        <stvoreno_u_radnom_odnosu>true</stvoreno_u_radnom_odnosu>
        <nacin_koriscenja></nacin_koriscenja>
        <anoniman_autor>false</anoniman_autor>
    </autorsko_delo>
    <prilozi>
        <prilog/>
    </prilozi>
    <zavod>
        <naziv></naziv>
        <adresa>
            <ulica></ulica>
            <broj>15</broj>
            <postanski_broj>21000</postanski_broj>
            <mesto></mesto>
            <drzava></drzava>
        </adresa>
    </zavod>
</zahtev>
